# Site settings
title: "shanshan"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: 874323976@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Roon was an excellent service, with a beautiful understated design. Roon
  was eventually acquired by Ghost, who awesomely chose to open source the theme.
  <br/>This is my Jekyll port of the Roon theme
url: "http://shanshan.work" # the base hostname & protocol for your site
twitter_username: wangshanshan
github_username:  wangshanshan

# Build settings
markdown: kramdown
